# Generated by Django 5.0.4 on 2024-04-04 17:23
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gemini', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
